const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Connections,PROVIDERS,psCommand}=require('./connections.cjs');
function setup(t,options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ruang-connection-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from('encrypted:'+Buffer.from(s).toString('base64')),decryptString:b=>Buffer.from(b.toString().replace('encrypted:',''),'base64').toString()};return new Connections({root,safeStorage,env:{PATH:''},...options})}
test('all three API adapters use fixed endpoints and headers; key never appears in public state',async t=>{for(const id of Object.keys(PROVIDERS)){let request;const c=setup(t,{fetchImpl:async(url,opts)=>{request={url,opts};return {ok:true,json:async()=>id==='gemini'?{models:[]}:{data:[]}}}});const key='test-private-credential-123';await c.saveKey(id,key);assert.equal(request.url,PROVIDERS[id].endpoint);assert.equal(request.opts.redirect,'error');assert.equal(request.opts.method,undefined);assert.equal(request.opts.body,undefined);assert.equal(request.opts.headers[id==='codex'?'Authorization':id==='claude'?'x-api-key':'x-goog-api-key'],id==='codex'?'Bearer '+key:key);assert(!JSON.stringify(c.list()).includes(key));assert(!fs.readFileSync(c.file,'utf8').includes(key));assert.equal(c.list().find(x=>x.id===id).status,'API verified');await c.checkAPI(id);c.disconnect(id);assert(!c.config[id].secret)}});
test('failed replacement preserves the previous encrypted key',async t=>{let ok=true;const c=setup(t,{fetchImpl:async()=>({ok,status:401,json:async()=>({data:[]})})});await c.saveKey('codex','original-key-123456');const secret=c.config.codex.secret;ok=false;await assert.rejects(c.saveKey('codex','replacement-key-123'),/rejected/);assert.equal(c.config.codex.secret,secret);await assert.rejects(c.checkAPI('codex'),/rejected/);assert.equal(c.list().find(x=>x.id==='codex').status,'Check failed')});
test('fails closed without OS encryption and never makes a request',async t=>{let called=false;const c=setup(t,{safeStorage:{isEncryptionAvailable:()=>false},fetchImpl:async()=>{called=true}});await assert.rejects(c.saveKey('claude','test-secret-123456'),/not saved/);assert.equal(called,false)});
test('network and provider response errors never echo secrets',async t=>{const secret='private-test-secret';const c=setup(t,{fetchImpl:async()=>{throw Error(secret)}});await assert.rejects(c.saveKey('gemini',secret),error=>!error.message.includes(secret)&&/internet/.test(error.message));c.fetch=async()=>({ok:true,json:async()=>({error:secret})});await assert.rejects(c.saveKey('gemini',secret),/unexpected/)});
test('unknown providers and control characters rejected',async t=>{const c=setup(t);await assert.rejects(c.saveKey('__proto__','test-secret-123'),/Unknown/);await assert.rejects(c.saveKey('codex','test-secret\n123'),/valid/);assert.throws(()=>c.disconnect('constructor'),/Unknown/)});
test('CLI login quotes paths and does not assume success',async t=>{let launched;const c=setup(t,{launch:async(...args)=>{launched=args}});const exe=path.join(c.root,"folder's tools");fs.mkdirSync(exe);const file=path.join(exe,'codex.exe');fs.writeFileSync(file,'test fixture');c.selectExecutable('codex',file);await c.login('codex');assert(launched[0].includes("folder''s tools"));assert(launched[0].includes("'login'"));assert.equal(c.list().find(x=>x.id==='codex').status,'Sign-in opened');assert(!c.config.codex.secret);c.disconnect('codex');assert.equal(c.list().find(x=>x.id==='codex').status,'Disconnected')});
test('status checks parse evidence and never return raw account output',async t=>{const c=setup(t,{run:async()=>({code:0,output:JSON.stringify({loggedIn:true,email:'private@example.com'})})});const file=path.join(c.root,'claude.exe');fs.writeFileSync(file,'fixture');c.selectExecutable('claude',file);c.config.claude={...c.config.claude,mode:'cli',enabled:true};let rows=await c.checkCLI('claude');assert.equal(rows.find(x=>x.id==='claude').status,'Signed in');assert(!JSON.stringify(rows).includes('private@example.com'));c.run=async()=>({code:0,output:'unsupported command'});rows=await c.checkCLI('claude');assert.equal(rows.find(x=>x.id==='claude').status,'Sign-in not verified')});
test('Gemini does not claim a verified session or silently send a paid prompt',async t=>{const c=setup(t,{run:async()=>{throw Error('Must not run')}});const file=path.join(c.root,'gemini.cmd');fs.writeFileSync(file,'fixture');c.selectExecutable('gemini',file);c.config.gemini={...c.config.gemini,mode:'cli',enabled:true};const rows=await c.checkCLI('gemini');assert.equal(rows.find(x=>x.id==='gemini').status,'Official sign-in required')});
test('concurrent changes cannot restore a disconnected or replaced key',async t=>{let finish;const c=setup(t,{fetchImpl:()=>new Promise(resolve=>{finish=resolve})});const saving=c.saveKey('codex','test-secret-123456');assert.throws(()=>c.disconnect('codex'),/Wait/);await assert.rejects(c.saveKey('codex','another-secret-1234'),/busy/);finish({ok:true,json:async()=>({data:[]})});await saving;c.disconnect('codex');assert.equal(c.config.codex.enabled,false)});
test('reopening does not treat stale verification as current',async t=>{const c=setup(t,{fetchImpl:async()=>({ok:true,json:async()=>({data:[]})})});await c.saveKey('codex','test-secret-123456');const second=new Connections({root:c.root,safeStorage:c.safeStorage,env:{PATH:''}});assert.equal(second.list().find(x=>x.id==='codex').status,'Saved · not checked')});
test('PowerShell arguments preserve literal metacharacters',()=>{assert.equal(psCommand("C:\\tools' folder\\codex.exe",['login','$(not-code)']),"& 'C:\\tools'' folder\\codex.exe' 'login' '$(not-code)'")});
