const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Workspace}=require('./workspace.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ai-office-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const folder=path.join(root,'project');fs.mkdirSync(folder);fs.writeFileSync(path.join(folder,'notes.md'),'Original\r\n');const workspace=new Workspace();workspace.select(folder);return {root,folder,workspace}}
test('reads, writes and preserves original backup',t=>{const {workspace,folder}=fixture(t);const before=workspace.read('notes.md');const saved=workspace.save({...before,content:'Updated\r\n'});assert.equal(fs.readFileSync(path.join(folder,'notes.md'),'utf8'),'Updated\r\n');assert.equal(fs.readFileSync(path.join(folder,saved.backup),'utf8'),'Original\r\n');assert.equal(workspace.list().entries.some(e=>e.name==='.ai-office-backups'),false)});
test('rejects traversal, absolute paths, secrets and oversized files',t=>{const {workspace,folder,root}=fixture(t);fs.writeFileSync(path.join(root,'outside.md'),'private');fs.writeFileSync(path.join(folder,'.env'),'secret');fs.writeFileSync(path.join(folder,'large.txt'),Buffer.alloc(1024*1024+1));for(const name of ['../outside.md',path.join(root,'outside.md'),'.env','large.txt','notes.md:stream'])assert.throws(()=>workspace.read(name));});
test('rejects edits if content changed on disk',t=>{const {workspace,folder}=fixture(t);const before=workspace.read('notes.md');fs.writeFileSync(path.join(folder,'notes.md'),'Another editor');assert.throws(()=>workspace.save({...before,content:'Overwrite'}),/changed on disk/);assert.equal(fs.readFileSync(path.join(folder,'notes.md'),'utf8'),'Another editor')});
test('rejects stale file after selecting another folder',t=>{const {workspace,root}=fixture(t);const before=workspace.read('notes.md');const second=path.join(root,'second');fs.mkdirSync(second);fs.writeFileSync(path.join(second,'notes.md'),'Original\r\n');workspace.select(second);assert.throws(()=>workspace.save({...before,content:'Wrong folder'}),/folder changed/)});
test('rejects directory junctions outside workspace',t=>{const {workspace,folder,root}=fixture(t);const outside=path.join(root,'outside');fs.mkdirSync(outside);fs.writeFileSync(path.join(outside,'secret.md'),'secret');fs.symlinkSync(outside,path.join(folder,'shortcut'),'junction');assert.throws(()=>workspace.read('shortcut/secret.md'),/Links/);assert.equal(workspace.list().entries.some(e=>e.name==='shortcut'),false)});
test('rejects binary and invalid UTF-8 rather than corrupting them',t=>{const {workspace,folder}=fixture(t);fs.writeFileSync(path.join(folder,'binary.txt'),Buffer.from([0,1,2]));fs.writeFileSync(path.join(folder,'legacy.txt'),Buffer.from([0xff,0xfe]));assert.throws(()=>workspace.read('binary.txt'));assert.throws(()=>workspace.read('legacy.txt'))});
test('preserves UTF-8 BOM on read and unchanged save',t=>{const {workspace,folder}=fixture(t);const buffer=Buffer.from('\ufeffhello');fs.writeFileSync(path.join(folder,'bom.txt'),buffer);const read=workspace.read('bom.txt');workspace.save(read);assert.deepEqual(fs.readFileSync(path.join(folder,'bom.txt')),buffer)});
